#!/bin/bash
cd "$(dirname "$0")"

die() {
  echo >&2 $1
  exit 1
}

usage() {
  echo -e >&2 "Usage: $0 deb output"
  exit 2
}

extract() {
    local deb=`readlink -f $1`
    local out=$2
    if [ ! -d "$out" ]; then
        mkdir $out
    fi
    local tmp=`mktemp -d`

    cd $tmp
    ar xv $deb || die "ar failed"
    if [ -f "data.tar.zst" ];then
        tar -I zstd -xf data.tar.* || die "tar failed"
    else
        tar xf data.tar.* || die "tar failed"
    fi
    find . -lname '/*' -exec sh -c '
        for link; do
            target=$(readlink "$link")
            echo target $target
            echo link $link
            link=${link#./}
            loc=$(dirname "$link")
            echo link $link
            root=$(realpath --relative-to="$loc" "./$target")
            echo root $root
        rm "$link"
        ln -s "${root#/}" "$link"
    done
    ' _ {} +
    cd -
    rsync -av -K $tmp/ $out

    #cp -rPT $tmp/ $out/  

    rm -rf $tmp
}

if [[ $# -ne 2 ]]; then
    usage
fi

extract "$1" "$2"


